gts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gtsmgr/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('pay/', include('pay.urls')),
    path('api/', include('api.urls')),
    path('msg/', include('msg.urls')),
    path('sell/', include('sell.urls')),
    path('chart/', include('api.chart.urls')),
    path('cardapi/', include('api.urls_flutter')),
    path('lock/', include('lock.urls')),
    path('blog/', include('blog.urls')),
    path('visit/', include('visit.urls')),
    path('cng/', include('cng.urls')),
    path('fuel_distribution/', include('fuel_distribution.urls')),
    path('notification/', include('notification.urls')),
    path('bazrasnegar/', include('bazrasnegar.urls')),
    path('automation/', include('automation.urls')),
    path('pm/', include('pm.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('silk/', include('silk.urls', namespace='silk')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path
from . import views, view_workshop
from base import autoexcel
from .views import RepairUse
from .view_repaire import view_repaire, add_repaire, liststoreyadaki, add_repaire_store, deletezone_repaire, \
    deletezone_repaire_store, uploadstore, downloadstore, addstorefunc, newstorefun, RepairRequestList, \
    delete_store_item, repairstorename, addstorename, repairparametrs, add_repairparametrs, plusstore

app_name = 'pay'

urlpatterns = [
    path('PayBase/', views.paybase, name='PayBase'),
    path('getPriod/', views.getpriod, name='getPriod'),
    path('getTekpay/', views.gettekpay, name='getTekpay'),
    path('CommitMgr/', views.commitmgr, name='CommitMgr'),
    path('acceptpay/<int:owner>/<int:period>/', views.acceptpay, name='acceptpay'),
    path('viewcommit/', views.viewcommit, name='viewcommit'),
    path('reportcommit/', views.reportcommit, name='reportcommit'),
    path('accesptmgr/<int:_id>/', views.accesptmgr, name='accesptmgr'),
    path('accesptmgr2/<int:_id>/<int:_zone>/', views.accesptmgr2, name='accesptmgr2'),
    path('accesptmgr3/<int:_id>/<int:_zone>/', views.accesptmgr3, name='accesptmgr3'),
    path('SendZone/', views.sendzone, name='SendZone'),
    path('SendZoneworkshop/', view_workshop.sendzoneworkshop, name='SendZoneworkshop'),
    path('sendlist/', views.sendlist, name='sendlist'),
    path('sendmarsole2/', views.sendmarsole2, name='sendmarsole2'),
    path('sendresid/', views.sendresid, name='sendresid'),
    path('sendall/', views.sendall, name='sendall'),
    path('PoshtibanList/', views.poshtibanlist, name='PoshtibanList'),
    path('residZone/', views.residzone, name='residZone'),
    path('AddStore/<int:_id>/<int:st>/', views.addstore, name='AddStore'),
    path('addmystore/', views.addmystore, name='addmystore'),
    path('fish/<int:period>/<int:_id>/', views.fish, name='fish'),
    path('sendmarsole/', views.sendmarsole, name='sendmarsole'),
    path('zonelistresid/', views.zonelistresid, name='zonelistresid'),
    path('zonelistdaghi/', views.zonelistdaghi, name='zonelistdaghi'),
    path('residmarsole/', views.residmarsole, name='residmarsole'),
    path('getMasterList/', views.getmasterlist, name='getMasterList'),
    path('getmasterresid/', views.getmasterresid, name='getmasterresid'),
    path('payParametr/', views.payparametr, name='payParametr'),
    path('payParametrSave/', views.payparametrsave, name='payParametrSave'),
    path('payZone/', views.payzone, name='payZone'),
    path('payTeksave/', views.payteksave, name='payTeksave'),
    path('history/', views.history, name='history'),
    path('showfish/', views.showfish, name='showfish'),
    path('getStore/', views.getstore, name='getStore'),
    path('getsenddaghi/', views.getsenddaghi, name='getsenddaghi'),
    path('getStoreTek/', views.getstoretek, name='getStoreTek'),
    path('getStoretoTek/', views.getstoretotek, name='getStoretoTek'),
    path('AddSTORETEK/', views.addstoretek, name='AddSTORETEK'),
    path('AddSTOREGS/', views.addstoregs, name='AddSTOREGS'),
    path('changestore/', views.changestore, name='changestore'),
    path('changestore2/', views.changestore2, name='changestore2'),
    path('RemoveSTORETEK/', views.removestoretek, name='RemoveSTORETEK'),
    path('storetotek/', views.storetotek, name='storetotek'),
    path('storetokargah/', views.storetokargah, name='storetokargah'),
    path('plombtozone/', views.plombtozone, name='plombtozone'),
    path('import_excel_store/<int:_id>/<int:zoneid>/', views.import_excel_store, name='import_excel_store'),
    path('updatezone/<int:_id>/', views.updatezone, name='updatezone'),
    path('deletezone/<int:_id>/', views.deletezone, name='deletezone'),
    path('okalert/<int:_id>/', views.okalert, name='okalert'),
    path('DastmozdToExcel/<int:_id>/<int:zone>/', views.dastmozdtoexcel, name='DastmozdToExcel'),
    path('tadiltoexcel/<int:_id>/<int:zone>/', views.tadiltoexcel, name='tadiltoexcel'),
    path('StoreToExcel/<int:_id>/<int:st>/', views.storetoexcel, name='StoreToExcel'),
    path('checkserial/', views.checkserial, name='checkserial'),
    path('getInformation/', views.getinformation, name='getInformation'),
    path('test/', views.test, name='test'),
    path('StartError/', views.starterr, name='StartError'),
    path('reporttekstore/', views.reporttekstore, name='reporttekstore'),
    path('reportzonestore/<int:_id>/', views.reportzonestore, name='reportzonestore'),
    path('getMasterListtek/', views.getmasterlisttek, name='getMasterListtek'),
    path('getstorelistzone/', views.getstorelistzone, name='getstorelistzone'),
    path('tek_amalkard/', views.tek_amalkard, name='tek_amalkard'),
    path('taeed/', views.taeed, name='taeed'),
    path('removeSerial/', views.removeserial, name='removeSerial'),
    path('removeSerial2/', views.removeserial2, name='removeSerial2'),
    path('reportstoe/', views.reportstoe, name='reportstoe'),
    path('TakhsisToExcel/<str:page_num>/', views.takhsistoexcel, name='TakhsisToExcel'),
    path('accepttedad/<int:_id>/', views.accepttedad, name='accepttedad'),
    path('historychange/<str:serial>/', views.historychange, name='historychange'),
    path('updateParametr/<int:postperiod>/', views.updateparametr, name='updateParametr'),
    path('checkzonestore/', views.checkzonestore, name='checkzonestore'),
    path('newstore/', views.newstore, name='newstore'),
    path('senddaghi/', views.senddaghi, name='senddaghi'),
    path('sendlistworkshop/', view_workshop.sendlistworkshop, name='sendlistworkshop'),
    path('add_daghi_to_kargah/', views.add_daghi_to_kargah, name='add_daghi_to_kargah'),
    path('store_mgr/', views.store_mgr, name='store_mgr'),
    path('store_detail_mgr/<str:mdate>/<str:mdate2>/<int:zoneid>/', views.store_detail_mgr, name='store_detail_mgr'),
    path('backtodaghi/<int:_id>/', views.backtodaghi, name='backtodaghi'),
    path('new_arzyabi/', views.new_arzyabi, name='new_arzyabi'),
    path('store_start_daghi/', views.store_start_daghi, name='store_start_daghi'),
    path('reportzonestore_toexcel/', views.reportzonestoretoexcel, name='reportzonestore_toexcel'),
    path('reportzonestore_toexcel2/', views.reportzonestoretoexcel2, name='reportzonestore_toexcel2'),
    path('changestatusscript/', views.changestatusscript, name='changestatusscript'),
    path('gotadil/', views.gotadil, name='gotadil'),
    path('rowtadil/<int:old>/<int:new>/', views.rowtadil, name='rowtadil'),
    path('RepairUse/', RepairUse.as_view(), name='RepairUse'),
    path('RepairRequestList/', RepairRequestList.as_view(), name='RepairRequestList'),
    path('scriptstore/', views.scriptstore, name='scriptstore'),
    path('scriptview/', views.scriptview, name='scriptview'),
    path('liststorekargah/', views.liststorekargah, name='liststorekargah'),
    path('import_excel_nazer/', views.import_excel_nazer, name='import_excel_nazer'),
    path('import_excel_kargah/<int:_id>/', views.import_excel_kargah, name='import_excel_kargah'),
    path('import_excel_changest/', views.import_excel_changest, name='import_excel_changest'),
    path('import_excel_residstore/<int:_id>/', views.import_excel_residstore, name='import_excel_residstore'),
    path('addstorerepair/<int:_id>/', views.addstorerepair, name='addstorerepair'),
    path('showimg/<int:_id>/', views.showimg, name='showimg'),
    path('historylist/<str:_id>/', views.historylist, name='historylist'),
    path('editstores/<str:serial>/', views.editstores, name='editstores'),
    path('mojodidaghikol/', views.mojodidaghikol, name='mojodidaghikol'),
    path('amarstorstek/', views.amarstorstek, name='amarstorstek'),
    path('serialliststore/', views.serialliststore, name='serialliststore'),
    path('countstoragezone/', views.countstoragezone, name='countstoragezone'),
    path('sendinkargah/', views.sendinkargah, name='sendinkargah'),
    path('amarstorstekdetail/<str:tarikh>/<str:tarikh2>/<int:owner>/', views.amarstorstekdetail,
         name='amarstorstekdetail'),
    path('view_repaire/', view_repaire, name='view_repaire'),
    path('add_repaire/', add_repaire, name='add_repaire'),
    path('liststoreyadaki/<int:_id>/', liststoreyadaki, name='liststoreyadaki'),
    path('uploadstore/', uploadstore, name='uploadstore'),
    path('downloadstore/<int:_id>/', downloadstore, name='downloadstore'),
    path('delete_zone_repaire/<int:_id>/', deletezone_repaire, name='delete_zone_repaire'),
    path('add_repaire_store/<int:_id>/', add_repaire_store, name='add_repaire_store'),
    path('delete_zone_repaire_store/<int:_id>/', deletezone_repaire_store, name='delete_zone_repaire_store'),
    path('addstorefunc/', addstorefunc, name='addstorefunc'),
    path('delete_store_item/', delete_store_item, name='delete_store_item'),
    path('newstorefun/', newstorefun, name='newstorefun'),
    path('repairstorename/', repairstorename, name='repairstorename'),
    path('addstorename/', addstorename, name='addstorename'),
    path('plusstore/', plusstore, name='plusstore'),
    path('repairparametrs/<int:_id>/', repairparametrs, name='repairparametrs'),
    path('updatestorezone/<int:_id>/', views.updatestorezone, name='updatestorezone'),
    path('add_repairparametrs/', add_repairparametrs, name='add_repairparametrs'),
    path('work_repair/', views.work_repair, name='work_repair'),
    path('storezonetoexcel/', autoexcel.storezonetoexcel, name='storezonetoexcel'),
    path('backtotakhsis/<int:_id>/', views.backtotakhsis, name='backtotakhsis'),
    path('import_excel_serialnumber/', views.import_excel_serialnumber, name='import_excel_serialnumber'),
    path('serialtoexcelauto/', autoexcel.serialtoexcelauto, name='serialtoexcelauto'),
    path('checkstoremanufactur/', views.checkstoremanufactur, name='checkstoremanufactur'),
    path('nemodarkamkarkard/', views.nemodarkamkarkard, name='nemodarkamkarkard'),
    path('nemodarkamkarkard2/', views.nemodarkamkarkard2, name='nemodarkamkarkard2'),

pm/urls.py
from django.urls import path
from . import views

app_name = 'pm'

urlpatterns = [
    path('<int:pk>/', views.station_detail, name='station_detail'),
    path('<int:station_pk>/checklist/create/', views.create_checklist, name='create_checklist'),
    path('checklist/<int:pk>/', views.checklist_detail, name='checklist_detail'),
]

pay/forms.py
from django import forms
from .models import Repair, ImgSerial, StoreList, RepairStoreName, RepairRole
from .models_repaire import Repaires, RepaireStores


class RepairForm(forms.ModelForm):
    class Meta:
        model = Repair
        fields = ['repairstore', 'valuecount']


class ImageStore(forms.ModelForm):
    class Meta:
        model = ImgSerial
        fields = ['img', ]


class StoreListForm(forms.ModelForm):
    class Meta:
        model = StoreList
        fields = {'statusstore', 'zone', 'status', 'serial', 'info'}
        labels = {'statusstore': 'نوع قطعه',
                  'zone': 'منطقه / کارگاه',
                  'status': 'وضعیت قطعه',
                  'serial': 'شماره سریال',
                  'info': 'توضیحات',
                  }


class RepqiresAddForm(forms.ModelForm):
    class Meta:
        model = Repaires
        fields = ['zone',]


class UploadAddForm(forms.ModelForm):
    class Meta:
        model = Repaires
        fields = ['marsole',]


class RepqiresAddStoreForm(forms.ModelForm):
    class Meta:
        model = RepaireStores
        fields = ['repairstore', 'amount']

class RepqireAddStoreName(forms.ModelForm):
    class Meta:
        model = RepairStoreName
        fields = ['name',]

class RepairParametrForm(forms.ModelForm):
    class Meta:
        model = RepairRole
        fields = ['minvalue','usevalue','startvalue']

pay/templates/repair/addrequeststore.html
{% extends 'base.html' %}
{% load static %}

{% block context %}
    <link rel="stylesheet" href="{% static 'vendors/select2/css/select2.min.css' %}" type="text/css">
    <link type="text/css" rel="stylesheet" href="{% static 'assets/css/jalalidatepicker.min.css' %} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/_pelak.css' %}"/>
    <script type="text/javascript" src="{% static 'assets/js/jalalidatepicker.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
    <style>

    </style>

    {% include 'message.html' %}


    <div class="card">
    <h3>لیست قطعات
<span>{{ zonename }}</span>
    </h3>



    <div class="card-body">
    <ul class="nav">

  &nbsp
  &nbsp
 <a style="color: white" class="btn btn-dark" href="{% url 'pay:view_repaire' %}">بازگشت</a>
     &nbsp
     &nbsp
{# {% if a == 1 %}#}
{#            <a class="btn nav-link bg-warning" data-target="#addstore" data-toggle="modal" title="درج قطعه"#}
{#             >#}
{#                <i data-feather="plus" aria-hidden="true"></i>جدید#}
{#            </a>#}
{##}
{#{% endif %}#}
  </li>
    </ul>
        <form action="" method="post">
    <div class="table-responsive">
        <table id="myTable" class="table table-striped ">
         <caption style="display: none">لیست قطعات</caption>
            <thead>
            <tr>
                <th scope="col">شرح</th>
                <th scope="col">تعداد</th>

                <th scope="col"></th>



            </tr>
            </thead>

          {% csrf_token %}
            <tbody>
            {% for g in stores %}
                <tr id="tr{{ g.id }}">
                <td>{{ g.repairstore.name }}</td>
                <td>{% if repaires.status_id == 1 %}<input style="width: 110px; background: #acfffd" id="id_amount" name="amount-{{ g.repairstore.id }}" type="number" class="form-control text-center" value="{{ g.amount }}">{% else %}{{ g.amount }}{% endif %}</td>
{#                <td>#}
{##}
{#                     {% if a == 1  %}#}
{#                    <a href="{% url 'pay:delete_zone_repaire_store' g.id %}" class="btn nav-link bg-danger" data-toggle="tooltip" title="حذف قطعه"#}
{#             >#}
{#                <i data-feather="trash" aria-hidden="true"></i>#}
{#            </a>{% endif %}#}
{#                </td>#}
                </tr>
{% endfor %}
            </tbody>
        </table>
    </div>

<div class="row">
<div class="col-5"></div>
<div class="col-3">
    {% if repaires.status_id == 1 %}
    <button type="submit" class="btn btn-success">ذخیره</button>
    {% endif %}
</div>
<div class="col-4"></div>
</div>
</form>

        <div class="modal fade" id="addstore" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div id="headerid" class="modal-header">
  <h3>لیست قطعات ارسالی</h3>

        </div>
<form action="{% url 'pay:add_repaire_store' storeid %}" method="post">
{% csrf_token %}
        <div class="modal-body">
<input type="hidden" id="id_storeid" name="sroreid">
<select name="repairstore" id="id_repairstore" class="form-control">
                            <option value="0">قطعه مورد نظر را انتخاب کنید</option>
                            {% for item in storename %}
                                <option
                                        value="{{ item.id }}">{{ item.name }} </option>
                            {% endfor %}
                        </select>
            <br>
            <input type="number" class="text-center form-control" id="id_amount" name="amount" placeholder="تعداد قطعه ارسالی">

        </div>

        <div class="modal-footer">
            <div id="fotteridclose">

                <button type="submit" class="btn btn-success">ذخیره</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
            </div>
        </div>
</form>
    </div>
    </div>
    </div>
            {# ##########################################################################################################################################           #}

    <input id="rowid" type="hidden" >


{% endblock %}
{% block script %}
    <script src="{% static 'assets/js/examples/datatable.js' %}"></script>
    {#    <script src="{% static 'vendors/dataTable/jquery.dataTables.min.js' %}"></script>#}
    <script src="{% static 'vendors/select2/js/select2.min.js' %}"></script>
    <!-- Bootstrap 4 and responsive compatibility -->
    <script src="{% static 'vendors/dataTable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/dataTable/dataTables.responsive.min.js' %}"></script>
<script>
    function FilterCardClose2(val) {

            document.getElementById('vore_id').value=val;
            document.getElementById('formsubmit').submit()
        }
</script>
    {% include 'script_pay.html' %}


    <script>

        jalaliDatepicker.startWatch();
        $('.select2-example').select2({
            placeholder: 'همه موارد',
            allowClear: true
        });
        $('.select2-example').select2({
            placeholder: 'Select'
        });
        $('.select3-example').select2({
            placeholder: 'Select'
        });
        $('.select4-example').select2({
            placeholder: 'Select'
        });
        $('.select5-example').select2({
            placeholder: 'Select'
        });
        $('.select6-example').select2({
            placeholder: 'Select'
        });
        $('.select7-example').select2({
            placeholder: 'Select'
        });

        function getFilter() {
            document.getElementById('FilterCard').style.display = "block";
        }




        function FilterCardCloseform() {
            document.getElementById('FilterCard').style.display = "none";
        }
         function rowidval(val){
            document.getElementById('rowid').value = val

            }



    </script>


{% endblock %}

pay/templates/repair/addstorerepaire.html
{% extends 'base.html' %}
{% load static %}

{% block context %}
    <link rel="stylesheet" href="{% static 'vendors/select2/css/select2.min.css' %}" type="text/css">
    {% include 'message.html' %}

    <div class="card">
        <div class="card body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <caption style="display: none">قطعات اولیه</caption>
                    <thead>
                    <tr>
                        <th class="text center">نام قطعه</th>
                        <th class="text center">تعداد درخواست</th>
                        <th class="text center">تعداد ارسال</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in store %}
                        <tr>
                            <td class="text center">{{ item.repairstore.name }}</td>
                            <td class="text center">{{ item.req }}</td>
                        <td><input class="form-control" type="text"></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            <div class="row">
                <div class="col-5"></div>
                <div class="col-3">
             <button class="btn btn-success">ذخیره</button>
                </div>
                <div class="col-5"></div>
                </div>
            </div>

        </div>

    </div>
    {#        <div class="card">#}
    {#            <div class="card body">#}
    {#                    #}
    {#                #}
    {#            </div>#}
    {#        </div>#}


{% endblock %}

pay/templates/repair/repairparametrs.html
{% extends 'base.html' %}
{% load static %}

{% block context %}
    <link rel="stylesheet" href="{% static 'vendors/select2/css/select2.min.css' %}" type="text/css">
    <link type="text/css" rel="stylesheet" href="{% static 'assets/css/jalalidatepicker.min.css' %} "/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/_pelak.css' %}"/>
    <script type="text/javascript" src="{% static 'assets/js/jalalidatepicker.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
    <style>

    </style>

    {% include 'message.html' %}


    <div class="card">
    <h3>لیست قطعات
<span>{{ zonename }}</span>
    </h3>



    <div class="card-body">
    <ul class="nav">

  &nbsp
  &nbsp
 <a style="color: white" class="btn btn-dark" href="{% url 'pay:view_repaire' %}">بازگشت</a>
     &nbsp
     &nbsp

            <a class="btn nav-link bg-warning" data-target="#addstore" data-toggle="modal" title="درج "
             >
                <i data-feather="plus" aria-hidden="true"></i>جدید
            </a>


  </li>
    </ul>
    <div class="table-responsive">
        <table id="myTable" class="table table-striped ">
         <caption style="display: none">لیست قطعات</caption>
            <thead>
            <tr>
                <th scope="col">نام کارگاه</th>
                <th scope="col">نام قطعه</th>
                <th scope="col">حداقل موجودی</th>
                <th scope="col">سقف ارسالی</th>
                <th scope="col">موجودی اولیه</th>

                <th scope="col"></th>



            </tr>
            </thead>
            <tbody>
            {% for g in list %}
                <tr id="tr{{ g.id }}">
                <td>{{ g.storage.name }}</td>
                <td>{{ g.repairstore.name }}</td>
                <td>{{ g.minvalue }}</td>
                <td>{{ g.usevalue }}</td>
                <td>{{ g.startvalue }}</td>
                      <td> <a  onclick="getidfun({{ g.id }},{{ g.minvalue }},{{ g.usevalue }},{{ g.startvalue }})" data-target="#uploadid" data-toggle="modal"  class="btn nav-link bg-success-gradient"  title="ویرایش اطلاعات پایه" >
                <i data-feather="edit" aria-hidden="true"></i>ویرایش
            </a>
                </td>

                </tr>
{% endfor %}
            </tbody>
        </table>
    </div>






    <input id="rowid" type="hidden" >

    <div class="modal fade" id="uploadid" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div id="headerid" class="modal-header">
  <h3>تعریف قطعه جدید</h3>

        </div>
    <form action="{% url 'pay:add_repairparametrs' %}" method="post">
    {% csrf_token %}
        <div class="modal-body">
            <input type="hidden" id="mystoreid" name="mystoreid">
            <label for="id_minvalue">حداقل موجودی</label>
            <input type="text" required name="minvalue" id="id_minvalue" class="form-control text-center">
                        <label for="id_minvalue">سقف ارسالی</label>
            <input type="text" required name="usevalue" id="id_usevalue" class="form-control text-center">
                        <label for="id_minvalue">موجودی اولیه</label>
            <input type="text" required name="startvalue" id="id_startvalue" class="form-control text-center">

        </div>

        <div class="modal-footer">
            <div id="fotteridclose">

                <button type="submit" class="btn btn-success">ذخیره</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </form>
    </div>
    </div>
    </div>

{% endblock %}
{% block script %}
    <script src="{% static 'assets/js/examples/datatable.js' %}"></script>
    {#    <script src="{% static 'vendors/dataTable/jquery.dataTables.min.js' %}"></script>#}
    <script src="{% static 'vendors/select2/js/select2.min.js' %}"></script>
    <!-- Bootstrap 4 and responsive compatibility -->
    <script src="{% static 'vendors/dataTable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/dataTable/dataTables.responsive.min.js' %}"></script>
<script>
    function FilterCardClose2(val) {

            document.getElementById('vore_id').value=val;
            document.getElementById('formsubmit').submit()
        }
</script>
    {% include 'script_pay.html' %}


    <script>
    function getidfun(val,val1,val2,val3){

        document.getElementById('id_minvalue').value = val1
        document.getElementById('id_usevalue').value = val2
        document.getElementById('id_startvalue').value = val3
        document.getElementById('mystoreid').value = val
    }

        jalaliDatepicker.startWatch();
        $('.select2-example').select2({
            placeholder: 'همه موارد',
            allowClear: true
        });
        $('.select2-example').select2({
            placeholder: 'Select'
        });
        $('.select3-example').select2({
            placeholder: 'Select'
        });
        $('.select4-example').select2({
            placeholder: 'Select'
        });
        $('.select5-example').select2({
            placeholder: 'Select'
        });
        $('.select6-example').select2({
            placeholder: 'Select'
        });
        $('.select7-example').select2({
            placeholder: 'Select'
        });

        function getFilter() {
            document.getElementById('FilterCard').style.display = "block";
        }




        function FilterCardCloseform() {
            document.getElementById('FilterCard').style.display = "none";
        }
         function rowidval(val){
            document.getElementById('rowid').value = val

            }



    </script>


{% endblock %}