base/urls.py
from django.urls import path
from . import views, reports, autoexcel, api
from .views import AddReInitial
from .urls_api import urlpatterns as api_urls
from api.captcha import captcha_view
from .views import (
    UpdateGsModelSejjeli, CreatePumpSejjeli, UpdateMakhzanSejjeli, CreateMakhzanSejjeli, UpdatePumpSejjeli,
    TicketAnalysisView
)


app_name = 'base'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('veryfi/', views.verify, name='veryfi'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('saveRoles/', views.saveroles, name='saveRoles'),
    path('UserProfile/q=<str:id>', views.userprofile, name='UserProfile'),
    path('saveImg/<int:id>', views.saveimg, name='saveImg'),
    path('import_excel/', views.import_excel, name='import_excel'),
    path('ComposeTicket/', views.composeticket, name='ComposeTicket'),
    path('ForwardTickets/', views.forwardtickets, name='ForwardTickets'),
    path('CrudeTickets/', views.crudetickets, name='CrudeTickets'),
    path('erjatotek/', views.erjatotek, name='erjatotek'),
    path('ClosedTickets/', views.closedtickets, name='ClosedTickets'),
    path('RoleTickets/', views.roletickets, name='RoleTickets'),
    path('MyTickets/', views.mytickets, name='MyTickets'),
    path('UserList/', views.userlist, name='UserList'),
    path('TicketToExcel/', autoexcel.tickettoexcel, name='TicketToExcel'),
    path('AddGSRelation/<str:id>/', views.addgsrelation, name='AddGSRelation'),
    path('GsEdit/<str:id>/', views.gsedit, name='GsEdit'),
    path('nazelsList/', views.nazelslist, name='nazelsList'),
    path('editNazel/', views.editnazel, name='editNazel'),
    path('editnazels/', views.editnazels, name='editnazels'),
    path('SaveeditNazel/<int:id>/', views.saveeditnazel, name='SaveeditNazel'),
    path('NazelsStatus/', views.nazelsstatus, name='NazelsStatus'),
    path('NazelsStatusByManategh/', views.nazelsstatusbymanategh, name='NazelsStatusByManategh'),
    path('NazelsStatusByNavahy/<str:id>/', views.nazelsstatusbynavahy, name='NazelsStatusByNavahy'),
    path('NazelsStatusByGS/<str:id>/', views.nazelsstatusbygs, name='NazelsStatusByGS'),
    path('gsTickets/<str:id>/', views.gstickets, name='gsTickets'),
    path('MasterPinPad_Tickets/<int:id>/', views.masterpinpadtickets, name='MasterPinPad_Tickets'),
    path('MasterPinpad_Ticketnahye/<str:id>/', views.masterpinpadticketnahye, name='MasterPinpad_Ticketnahye'),
    path('MasterPinpad_TicketGs/<str:id>/', views.masterpinpadticketgs, name='MasterPinpad_TicketGs'),
    path('save_star/<int:id>/', views.save_star, name='save_star'),
    path('amarkharabigs/', views.amarkharabigs, name='amarkharabigs'),
    path('gssakoook/', views.gssakoook, name='gssakoook'),
    path('gssakoook2/', views.gssakoook2, name='gssakoook2'),
    path('import_excel_paydari/', views.import_excel_paydari, name='import_excel_paydari'),
    path('vieweditnazels/<int:id>/', views.vieweditnazels, name='vieweditnazels'),
    path('CrudeTicketstek/<int:id>/<int:code>/', views.crudeticketstek, name='CrudeTicketstek'),
    path('ckpaydari/', views.ckpaydari, name='ckpaydari'),
    path('master_pinpad_tickets_Toexcel/<int:_id>/', views.masterpinpadticketstoexcel,
         name='master_pinpad_tickets_Toexcel'),
    path('rep_napaydari/', views.rep_napaydari, name='rep_napaydari'),
    path('graph_ticket/', views.graph_ticket, name='graph_ticket'),
    path('reportticketdaily/', views.reportticketdaily, name='reportticketdaily'),
    path('gs_detail/<str:id>/', views.gs_detail, name='gs_detail'),
    path('export_ticket_xls/', views.export_ticket_xls, name='export_ticket_xls'),
    path('sendticketrpm/', views.sendticketrpm, name='sendticketrpm'),
    path('gs_list_arbain/', views.gs_list_arbain, name='gs_list_arbain'),
    path('listgs/', views.listgs, name='listgs'),
    path('gs-import-file/<int:id>/', views.gsimportfile, name='gs-import-file'),
    path('gs-import-sejelli/<int:id>/', views.gsimportsejelli, name='gs-import-sejelli'),
    path('gs-import-flouk/<int:id>/', views.gsimportflouk, name='gs-import-flouk'),
    path('reportipc/', views.reportipc, name='reportipc'),
    path('reportipchistort/<int:_id>/', views.reportipchistort, name='reportipchistort'),
    path('repnazelgs/', views.repnazelgs, name='repnazelgs'),
    path('updatesetting/', views.updatesetting, name='updatesetting'),
    path('reportgsticketmgr/<str:_id>/<str:_az>/<str:_ta>/', reports.reportgsticketmgr, name='reportgsticketmgr'),
    path('reportzoneticketmgr/', reports.reportzoneticketmgr, name='reportzoneticketmgr'),
    path('reporttecnesianmgr/', reports.reporttecnesianmgr, name='reporttecnesianmgr'),
    path('reportareaticketmgr/<str:_id>/<str:_az>/<str:_ta>/', reports.reportareaticketmgr, name='reportareaticketmgr'),
    path('sla/', views.sla, name='sla'),
    path('arealist/', views.arealist, name='arealist'),
    path('citylist/', views.citylist, name='citylist'),
    path('averagetickets/<int:id>/', views.averagetickets, name='averagetickets'),
    path('areaupdate/<int:_id>/', views.areaupdate, name='areaupdate'),
    path('cityupdate/<int:_id>/', views.cityupdate, name='cityupdate'),
    path('send_bulk_ticket/', views.send_bulk_ticket, name='send_bulk_ticket'),
    path('close_bulk_ticket/', views.close_bulk_ticket, name='close_bulk_ticket'),
    path('delete_bulk_ticket/', views.delete_bulk_ticket, name='delete_bulk_ticket'),
    path('autoclose_bulk_ticket/', views.autoclose_bulk_ticket, name='autoclose_bulk_ticket'),
    path('input_zone_table/', views.input_zone_table, name='input_zone_table'),
    path('input_coding_table/', views.input_coding_table, name='input_coding_table'),
    path('reportsla/', views.reportsla, name='reportsla'),
    path('checkipclog/', views.checkipclog, name='checkipclog'),
    path('addclosegs/<str:id>/', views.addclosegs, name='addclosegs'),
    path('addmoghgs/<str:id>/', views.addmoghgs, name='addmoghgs'),
    path('updateclosegs/<str:id>/', views.updateclosegs, name='updateclosegs'),
    path('updatemoghgs/<str:id>/', views.updatemoghgs, name='updatemoghgs'),
    path('reportnesbatgs/', reports.reportnesbatgs, name='reportnesbatgs'),
    path('storehistory/', views.storehistory, name='storehistory'),
    path('reportsla_conflig/', views.reportsla_conflig, name='reportsla_conflig'),
    path('technicianperformancereport/', views.technicianperformancereport, name='technicianperformancereport'),
    # path('autolocation/', views.autolocation, name='autolocation'),
    # path('newautolocation/', views.newautolocation, name='newautolocation'),
    path('gslogs/<str:_id>/', views.gslogs, name='gslogs'),
    path('ownerlogs/<str:_id>/', views.ownerlogs, name='ownerlogs'),
    path('tekprofile/<str:_id>/', views.tekprofile, name='tekprofile'),
    path('tekprofiles2/<str:_id>/', views.tekprofiles2, name='tekprofiles2'),
    path('tekprofiles3/<str:_id>/', views.tekprofiles3, name='tekprofiles3'),
    path('deletetekchild/<str:_id>/', views.deletetekchild, name='deletetekchild'),
    path('showimg/<int:_id>/<int:_st>/', views.showimg, name='showimg'),
    path('uploadownerfile/<int:_id>/<int:ownerid>/', views.uploadownerfile, name='uploadownerfile'),
    path('import_excel_gsinfo/', views.import_excel_gsinfo, name='import_excel_gsinfo'),
    path('check_tek_store/<int:_id>/', views.check_tek_store, name='check_tek_store'),
    path('import_arbain/', views.import_arbain, name='import_arbain'),
    path('reportSellticket/', views.reportSellticket, name='reportSellticket'),
    path('nesbat_tickets/<int:id>/', reports.nesbat_tickets, name='nesbat_tickets'),
    path('import_excel_mojodi/', views.import_excel_mojodi, name='import_excel_mojodi'),
    path('gsmalek/', views.gsmalek, name='gsmalek'),
    path('listreinitial/', views.listreinitial, name='listreinitial'),
    path('addreinitial/<int:pk>/', AddReInitial.as_view(), name='addreinitial'),
    path('acceptreinitial/<int:pk>/<int:st>/', views.acceptreinitial, name='acceptreinitial'),
    path('autoexcel/', autoexcel.autoexcel, name='autoexcel'),
    path('tryopenticket/<int:_id>/', views.tryopenticket, name='tryopenticket'),
    path('deleteticket/<int:_id>/', views.deleteticket, name='deleteticket'),
    path('mgrdashboard/', views.mgrdashboard, name='mgrdashboard'),
    path('pump_report/', views.pump_report, name='pump_report'),
    path('deleteclosesell/<int:_id>/', views.deleteclosesell, name='deleteclosesell'),
    path('parametrsgs/<str:_gsid>/<int:_id>/', views.parametrsgs, name='parametrsgs'),
    path('reportchardsh/', views.reportchardsh, name='reportchardsh'),
    path('captcha/', captcha_view, name='captcha_view'),
    path('my_view/', views.my_view, name='my_view'),
    path('schematic/<str:_id>/', views.schematic, name='schematic'),
    path('failure_analysis_report/', views.failure_analysis_report, name='failure_analysis_report'),
    path('gs/<int:gs_id>/sejelli/', views.manage_sejelli, name='manage_sejelli'),
    path('sejelli/<int:sejelli_id>/', views.sejelli_detail, name='sejelli_detail'),
    path('gs-sejelli/<int:pk>/edit/', UpdateGsModelSejjeli.as_view(), name='update_gs_sejelli'),
    path('sejelli/<int:sejelli_id>/pump/add/', CreatePumpSejjeli.as_view(), name='create_pump_sejelli'),
    path('pump-sejelli/<int:pk>/edit/', UpdatePumpSejjeli.as_view(), name='update_pump_sejelli'),
    path('sejelli/<int:sejelli_id>/makhzan/add/', CreateMakhzanSejjeli.as_view(), name='create_makhzan_sejelli'),
    path('ticket-analysis_re/', views.ticket_analysis_report, name='ticket_analysis_re'),
    path(
        'makhzan-sejelli/<int:sejelli_id>/update/<str:pk>/',
        UpdateMakhzanSejjeli.as_view(),
        name='update_makhzan_sejelli'
    ),
    path('pending_sejelli/', views.pending_sejelli_list, name='pending_sejelli_list'),
    path('sejelli_changes/<int:sejelli_id>/', views.sejelli_changes, name='sejelli_changes'),

gts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gtsmgr/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('pay/', include('pay.urls')),
    path('api/', include('api.urls')),
    path('msg/', include('msg.urls')),
    path('sell/', include('sell.urls')),
    path('chart/', include('api.chart.urls')),
    path('cardapi/', include('api.urls_flutter')),
    path('lock/', include('lock.urls')),
    path('blog/', include('blog.urls')),
    path('visit/', include('visit.urls')),
    path('cng/', include('cng.urls')),
    path('fuel_distribution/', include('fuel_distribution.urls')),
    path('notification/', include('notification.urls')),
    path('bazrasnegar/', include('bazrasnegar.urls')),
    path('automation/', include('automation.urls')),
    path('pm/', include('pm.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('silk/', include('silk.urls', namespace='silk')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pm/urls.py
from django.urls import path
from . import views

app_name = 'pm'

urlpatterns = [
    path('<int:pk>/', views.station_detail, name='station_detail'),
    path('<int:station_pk>/checklist/create/', views.create_checklist, name='create_checklist'),
    path('checklist/<int:pk>/', views.checklist_detail, name='checklist_detail'),
]

base/templates/dashboard/views/dashboardengin.py
import time
from datetime import date
from django.utils import timezone
from .dashboarditems import get_newticketstatus, get_me_ticket, \
    get_slider_items, get_napaydari_list, get_close_ticket_engin, get_pending_ticket_engin


def dashboardzone(_refrenceid, _roleid, request):
    _today = date.today()
    _today2 = time.time()
    today = timezone.now().date()
    _today = date.today()
    try:
        count_me, listmeticket = get_me_ticket(request)
        openticket, openticketyesterday, listopenticket = get_pending_ticket_engin(request, _today)
        closeticket, listcloseticket = get_close_ticket_engin(request, today)
        count_unit = get_newticketstatus(request)
        napydarilist = get_napaydari_list(request)
        rpm, napaydari, date_nosell, nosell, gscount, nazelcount, stars, napaydari_today = get_slider_items(request)
    except:

        return False

    return {'count_me': count_me, 'listmeticket': listmeticket, 'openticket': openticket,
            'openticketyesterday': openticketyesterday, 'listopenticketcloseticket': listopenticket,
            'closeticket': closeticket, 'listcloseticket': listcloseticket, 'count_unit': count_unit,
            'napaydari_list': napydarilist,
            'rpm': rpm, 'napaydari': napaydari, 'date_nosell': date_nosell, 'nosell': nosell, 'gscount': gscount,
            'nazelcount': nazelcount, 'stars': stars, 'napaydari_today': napaydari_today

            }

base/templates/report/MasterPinPad_Tickets.html
{% extends 'base.html' %}
{% load static %}
{% load basefiltertag %}
{% block context %}
    <script src="{% static 'assets/js/tableToExcel.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'assets/css/jalalidatepicker.min.css' %} "/>
    <script type="text/javascript" src="{% static 'assets/js/jalalidatepicker.min.js' %}"></script>
    <style>

    </style>
<div class="card">
<div class="card-body">
<p>انتخاب تاریخ جهت مشاهده  وضعیت تیکت ها در روزهای قبل</p>
     <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-1 col-md-1 col-sm-1"></div>
        <div class="col-lg-2 col-md-5 col-sm-12">
            <label>انتخاب تاریخ
                <input required data-jdp type="text" name="select" id="select" value="{{ tarikh }}" class="form-control"
                       placeholder="تاریخ" autocomplete="off">
            </label>

            <label for="id_hour">ساعت
            <select name="hour" id="id_hour" class="form-control">
                <option {% if hour == "-" %}selected{% endif %} value="-">-</option>
                <option {% if hour == "00" %}selected{% endif %} value="00">0</option>
                <option {% if hour == "01" %}selected{% endif %} value="01">1</option>
                <option {% if hour == "02" %}selected{% endif %} value="02">2</option>
                <option {% if hour == "03" %}selected{% endif %} value="03">3</option>
                <option {% if hour == "04" %}selected{% endif %} value="04">4</option>
                <option {% if hour == "05" %}selected{% endif %} value="05">5</option>
                <option {% if hour == "06" %}selected{% endif %} value="06">6</option>
                <option {% if hour == "07" %}selected{% endif %} value="07">7</option>
                <option {% if hour == "08" %}selected{% endif %} value="08">8</option>
                <option {% if hour == "09" %}selected{% endif %} value="09">9</option>
                <option {% if hour == "10" %}selected{% endif %} value="10">10</option>
                <option {% if hour == "11" %}selected{% endif %} value="11">11</option>
                <option {% if hour == "12" %}selected{% endif %} value="12">12</option>
                <option {% if hour == "13" %}selected{% endif %} value="13">13</option>
                <option {% if hour == "14" %}selected{% endif %} value="14">14</option>
                <option {% if hour == "15" %}selected{% endif %} value="15">15</option>
                <option {% if hour == "16" %}selected{% endif %} value="16">16</option>
                <option {% if hour == "17" %}selected{% endif %} value="17">17</option>
                <option {% if hour == "18" %}selected{% endif %} value="19">18</option>
                <option {% if hour == "19" %}selected{% endif %} value="19">19</option>
                <option {% if hour == "20" %}selected{% endif %} value="20">20</option>
                <option {% if hour == "21" %}selected{% endif %} value="21">21</option>
                <option {% if hour == "22" %}selected{% endif %} value="22">22</option>
                <option {% if hour == "23" %}selected{% endif %} value="23">23</option>
            </select></label>
            </div>
            <div class="m-3 col-lg-4 col-md-4 col-sm-12">
            <button style="color: #FFFFFF" type="submit" id="exportBtn12" class="btn btn-primary">ایجاد گزارش</button>

            <a href="{% url 'base:master_pinpad_tickets_Toexcel' 1 %}" id="exportBtn12" class="btn btn-warning">
                <i class="fa fa-file-excel-o"></i>
                خروجی
                اکسل </a>
            </div>
            <div class="col-lg-5 col-md-4 col-sm-12"></div>
        </div>

    </form>
</div>
</div>
    {% include 'message.html' %}

    <div class="card">
<form action="" method="get">  <!-- تغییر به method="get" -->
    <!-- سایر فیلدهای موجود -->

    <div class="col-lg-4 col-md-4 col-sm-12">
        <label for="product">فرآورده</label>
        <select name="product" id="id_product" class="select2-example" multiple>
            {% for product in products %}
                <option value="{{ product.id }}"
                    {% if product.id|stringformat:"s" in selected_products %}selected{% endif %}>
                    {{ product.name }}
                </option>
            {% endfor %}
        </select>
     <button type="submit" class="btn btn-primary">اعمال فیلتر</button>
    </div>


</form>


    <br>

    <div class="card-body">

    <div class="table-responsive">
    <table id="myTable" class="table table-striped table-bordered">
    <ul class="nav">
{#        <li class="nav-item">#}
{#            <button id="btnfilters" onclick="getFilter()" class="btn btn-success" title="فیلتر "#}
{#               data-toggle="tooltip">#}
{#                <i data-feather="filter" aria-hidden="true"></i>#}
{#            </button>#}
{##}
{#        </li>#}

<li class="nav-item">
     <button onclick="exportToExcelWithBorders()"  id="exportBtn1" class="btn btn-light" title="ارسال به اکسل این جدول" data-toggle="tooltip">
         <i class="fa fa-file-excel-o" style="font-size:18px;color:darkgreen"></i>
                 </button>
          </li>
    </ul>
     <caption style="display: none">گزارش وضعیت خرابی</caption>
        <thead>
        <tr>

             <th scope="col"  class="text-center">ردیف</th>
             <th scope="col"  class="text-center">منطقه</th>
             <th scope="col"  class="text-center">تعداد جایگاه</th>
             <th scope="col"  class="text-center">تعداد نازل</th>
             <th scope="col"  class="text-center">تعداد تیکت ها</th>
             <th scope="col"  class="text-center">تعداد تیکت کارتخوان</th>
             <th scope="col"  class="text-center">تعداد تیکت صفحه کلید</th>
             <th scope="col"  class="text-center">
                {% if id == 1 %}<i data-feather="arrow-down" aria-hidden="true"></i>{% endif %}
                <a href="{% url 'base:MasterPinPad_Tickets' 1 %}">درصد خرابی کارتخوان</a>
            </th>


             <th scope="col"  class="text-center">
                {% if id == 2 %}<i data-feather="arrow-down" aria-hidden="true"></i>{% endif %}
                <a href="{% url 'base:MasterPinPad_Tickets' 2 %}">درصد خرابی صفحه کلید</a>
            </th>
             <th scope="col"  class="text-center">
                {% if id == 3 %}<i data-feather="arrow-down" aria-hidden="true"></i>{% endif %}
                <a href="{% url 'base:MasterPinPad_Tickets' 3 %}"> مجموع درصد خرابی</a>
            </th>


        </tr>
        </thead>


        {% for item in list %}
            {##}
            <tr {% if item.st == 1 %} style="background-color: #c3e7a5; color: black" {% elif item.st == 2 %}
                                      style="background-color: #4ba2e4; color: black" {% endif %}>
                {% if item.name == 'مجموع' %}
                    <td class="text-center">-</td>
                    <td class="text-center">
                        <l6>{{ item.name }}</l6>
                    </td>

                {% else %}
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center"><a href="{% url 'base:MasterPinpad_Ticketnahye' item.id|to_md5 %}">
                        <l6>{{ item.name }}</l6>
                    </a></td>

                {% endif %}

                <td class="text-center">{{ item.count_gs }}</td>
                <td class="text-center">{{ item.count_pump }}</td>
                <td class="text-center">{{ item.count_ticket }}</td>
                <td class="text-center">{{ item.count_master }}</td>
                <td class="text-center">{{ item.count_pinpad }}</td>
                <td class="text-center">{{ item.master }}</td>
                <td class="text-center">{{ item.pinpad }}</td>
                <td class="text-center">{{ item.summ }}</td>

            </tr>

        {% endfor %}
        </tfoot>
    </table>

{% endblock %}
{% block script %}
    <script src="{% static 'assets/js/examples/datatable.js' %}"></script>

    <script src="{% static 'vendors/dataTable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/dataTable/dataTables.responsive.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            jalaliDatepicker.startWatch();
            $("#exportBtn11").click(function () {
                TableToExcel.convert(document.getElementById("myTable"), {
                    name: "list.xlsx",
                    sheet: {
                        name: "Sheet1"
                    }
                });
            });
        });
                $('.select2-example').select2({
            placeholder: 'Select'
        });
         function getFilter() {
            document.getElementById('FilterCard').style.display = "block";
            document.getElementById('btnfilters').style.display = "none";
        }

        function FilterCardClose() {
            document.getElementById('FilterCard').style.display = "none";
            document.getElementById('isfilter').value = '1'
            document.getElementById('btnfilters').style.display = "block";
        }

        function FilterCardCloseform() {
            document.getElementById('FilterCard').style.display = "none";
            document.getElementById('btnfilters').style.display = "block";
        }
        function gofilter(){
             document.getElementById('idval').value = "0"
            document.getElementById('formsub').submit()
        }
    </script>

{% endblock %}

base/templates/report/MasterPinpad_TicketGs.html
{% extends 'base.html' %}
{% load static %}
{% load basefiltertag %}
{% block context %}
    <script src="{% static 'assets/js/tableToExcel.js' %}"></script>
    <style>

    </style>

    {% include 'message.html' %}
    <div id="FilterCard" style="display: none" class="card">
        <div class="card-body text-center">
            <h4>فیلترها </h4>
        </div>
        <form action="">
            <hr class="m-0">
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <label for="zone">انتخاب مناطق </label>
                        <select name="zone" id="id_zone" class="select2-example" multiple>
                            {% for item in filter.form.zone %}
                                {{ item }}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <label for="area">انتخاب نواحی </label>
                        <select name="area" id="id_area" class="select3-example" multiple>
                            {% for item in filter.form.area %}
                                {{ item }}
                            {% endfor %}
                        </select>
                    </div>



                </div>
                <div></div>
                <hr>
                <button style="color: #f3fdf3" id="FilterCardClose" onclick="FilterCardClose()" type="submit"
                        class="btn nav-link bg-warning"> نمایش نتایج
                </button>
                <a style="color: #f3fdf3" onclick="FilterCardCloseform()"
                   class="btn nav-link bg-dark-bright">بستن
                </a>
            </div>

        </form>
    </div>
    <div class="card">
     <div class="col-4">
  <a onclick="exportToExcelWithBorders()" id="exportBtn1"  class="btn btn-warning">خروجی اکسل </a>
    </div>
    <br>
    <div class="card-body">
    <div class="table-responsive">
    <table id="myTable" class="table table-striped table-bordered">
     <caption style="display: none">وضعیت تیکت های جایگاه</caption>
        <thead>
        <tr>

             <th scope="col"  class="text-center">ردیف</th>
             <th scope="col"  class="text-center">کد جایگاه</th>
             <th scope="col"  class="text-center">جایگاه</th>
             <th scope="col"  class="text-center">تعداد نازل</th>
             <th scope="col"  class="text-center">تعداد تیکت ها</th>
             <th scope="col"  class="text-center">تعداد تیکت کارتخوان</th>
             <th scope="col"  class="text-center">تعداد تیکت صفحه کلید</th>
             <th scope="col"  class="text-center">درصد خرابی کارتخوان</th>
             <th scope="col"  class="text-center">درصد خرابی صفحه کلید</th>
                       <th scope="col"  class="text-center">مجموع درصد خرابی</th>



        </tr>
        </thead>


        {% for item in list %}
{##}
             <tr {% if item.st == 1 %} style="background-color: #c3e7a5; color: black" {% elif item.st == 2 %} style="background-color: #4ba2e4; color: black" {% endif %}>

                <td class="text-center">{{ forloop.counter }}</td>
                 <td class="text-center"><a href="{% url 'base:gsTickets' item.gsid|to_md5 %}">{{ item.gsid}}</a></td>
                 <td class="text-center"><a href="{% url 'base:gsTickets' item.gsid|to_md5 %}">{{ item.name}}</a></td>
                <td class="text-center">{{ item.count_pump }}</td>
                <td class="text-center">{{ item.count_ticket }}</td>
                <td class="text-center">{{ item.count_master }}</td>
                <td class="text-center">{{ item.count_pinpad }}</td>
                <td class="text-center">{{ item.master }}</td>
                <td class="text-center">{{ item.pinpad }}</td>
                    <td class="text-center">{{ item.summ }}</td>

            </tr>

        {% endfor %}
        </tfoot>
    </table>

{% endblock %}
{% block script %}
    <script src="{% static 'assets/js/examples/datatable.js' %}"></script>

    <script src="{% static 'vendors/dataTable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/dataTable/dataTables.responsive.min.js' %}"></script>


            <script type="text/javascript">
  $(document).ready(function () {
      $("#exportBtn11").click(function(){
        TableToExcel.convert(document.getElementById("myTable"), {
            name: "list.xlsx",
            sheet: {
            name: "Sheet1"
            }
          });
        });
  });
</script>
{% endblock %}